### ISSUE TITLE
Setting projection_hemisphere_id in ModelData.get_voxel_data()

### ISSUE THREAD

**Issue by sjkoelle** [AllenInstitute/mouse_connectivity_models#48]
The ModelData.get_voxel_data() function is missing the ability to pass projection_hemisphere_id to VoxelData as a kwarg.

**Comment by kharris** [comment]
I'd characterize this as a feature request. Given a voxel array, you can use a mask to pull one hemisphere's data out (or even use direct indexing).

**Comment by sjkoelle** [comment]
thanks!
